"""
    This is a dictionary of the moves and their power inside Pokemon Go.
"""



moves_dict = {
# '': {'DPS': '', 'Energy Cost': 0, 'Energy Per Hit': 0, 'Type': ''},
 u'Acid': {'DPS': 11.9,
  'Duration': 1050.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 12.5,
  'Type': u'Poison'},
 u'Aerial Ace': {'DPS': 9.05,
  'Duration': 2900.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Flying'},
 u'Air Cutter': {'DPS': 11.84,
  'Duration': 3300.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Flying'},
 u'Ancient Power': {'DPS': 10.94,
  'Duration': 3600.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Rock'},
 u'Aqua Jet': {'DPS': 6.7,
  'Duration': 2350.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 18.75,
  'Type': u'Water'},
 u'Aqua Tail': {'DPS': 27.93,
  'Duration': 2350.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Water'},
 u'Bite': {'DPS': 12.0,
  'Duration': 500.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 6.0,
  'Type': u'Dark'},
 u'Blizzard': {'DPS': 16.15,
  'Duration': 3900.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 60.0,
  'Type': u'Ice'},
 u'Body Slam': {'DPS': 42.07,
  'Duration': 1560.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Normal'},
 u'Bone Club': {'DPS': 13.13,
  'Duration': 1600.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Ground'},
 u'Brick Break': {'DPS': 23.44,
  'Duration': 1600.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 30.0,
  'Type': u'Fight'},
 u'Brine': {'DPS': 10.94,
  'Duration': 2400.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Water'},
 u'Bubble': {'DPS': 8.15,
  'Duration': 2300.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 15.0,
  'Power': 18.75,
  'Type': u'Water'},
 u'Bubble Beam': {'DPS': 9.05,
  'Duration': 2900.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Water'},
 u'Bug Bite': {'DPS': 16.7,
  'Duration': 450.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 7.5,
  'Type': u'Bug'},
 u'Bug Buzz': {'DPS': 12.35,
  'Duration': 4250.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Bug'},
 u'Bulldoze': {'DPS': 11.58,
  'Duration': 3400.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Ground'},
 u'Bullet Punch': {'DPS': 8.33,
  'Duration': 1200.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 7.0,
  'Power': 10.0,
  'Type': u'Steel'},
 u'Confusion': {'DPS': 7.95,
  'Duration': 1510.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 12.0,
  'Type': u'Psychic'},
 u'Cross Chop': {'DPS': 34.38,
  'Duration': 2000.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 55.0,
  'Type': u'Fight'},
 u'Cross Poison': {'DPS': 16.67,
  'Duration': 1500.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 0,
  'Power': 20.0,
  'Type': u'Poison'},
 u'Cut': {'DPS': 13.3,
  'Duration': 1130.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 7.0,
  'Power': 15.0,
  'Type': u'Normal'},
 u'Dark Pulse': {'DPS': 13.5,
  'Duration': 3500.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 45.0,
  'Type': u'Normal'},
 u'Dazzling Gleam': {'DPS': 11.25,
  'Duration': 4200.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 56.25,
  'Type': u'Fairy'},
 u'Dig': {'DPS': 8.15,
  'Duration': 5800.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 45.0,
  'Type': u'Ground'},
 u'Disarming Voice': {'DPS': 5.38,
  'Duration': 3900.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Fairy'},
 u'Discharge': {'DPS': 16.8,
  'Duration': 2500.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 50.0,
  'Type': u'Electric'},
 u'Dragon Breath': {'DPS': 12.0,
  'Duration': 500.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 6.0,
  'Type': u'Dragon'},
 u'Dragon Claw': {'DPS': 33.33,
  'Duration': 1500.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 40.0,
  'Type': u'Dragon'},
 u'Dragon Pulse': {'DPS': 14.58,
  'Duration': 3600.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 50.0,
  'Type': u'Dragon'},
 u'Draining Kiss': {'DPS': 5.63,
  'Duration': 2800.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 0,
  'Power': 15.0,
  'Type': u'Fairy'},
 u'Drill Peck': {'DPS': 14.58,
  'Duration': 2700.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Flying'},
 u'Drill Run': {'DPS': 14.71,
  'Duration': 3400.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 40.0,
  'Type': u'Ground'},
 u'Earthquake': {'DPS': 15.0,
  'Duration': 4200.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Ground'},
 u'Ember': {'DPS': 11.9,
  'Duration': 1050.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 12.5,
  'Type': u'Fire'},
 u'Feint Attack': {'DPS': 11.5,
  'Duration': 1040.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 7.0,
  'Power': 12.0,
  'Type': u'Dark'},
 u'Fire Blast': {'DPS': 15.37,
  'Duration': 4100.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Fire'},
 u'Fire Fang': {'DPS': 10.4,
  'Duration': 840.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 4.0,
  'Power': 8.75,
  'Type': u'Fire'},
 u'Fire Punch': {'DPS': 13.13,
  'Duration': 2800.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 43.75,
  'Type': u'Fire'},
 u'Flame Burst': {'DPS': 15.63,
  'Duration': 2100.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Fire'},
 u'Flame Charge': {'DPS': 6.77,
  'Duration': 3100.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Fire'},
 u'Flame Wheel': {'DPS': 7.99,
  'Duration': 4600.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 43.75,
  'Type': u'Fire'},
 u'Flamethrower': {'DPS': 22.63,
  'Duration': 2900.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Fire'},
 u'Flash Cannon': {'DPS': 14.81,
  'Duration': 3900.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 55.0,
  'Type': u'Steel'},
 u'Frost Breath': {'DPS': 18.5,
  'Duration': 810.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 15.0,
  'Type': u'Ice'},
 u'Fury Cutter': {'DPS': 7.5,
  'Duration': 400.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 12.0,
  'Power': 3.0,
  'Type': u'Bug'},
 u'Gunk Shot': {'DPS': 26.25,
  'Duration': 3000.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Poison'},
 u'Heat Wave': {'DPS': 16.58,
  'Duration': 3800.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Fire'},
 u'Horn Attack': {'DPS': 9.55,
  'Duration': 2200.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 20.0,
  'Type': u'Normal'},
 u'Hurricane': {'DPS': 19.69,
  'Duration': 3200.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Flying'},
 u'Hydro Pump': {'DPS': 20.72,
  'Duration': 3800.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Water'},
 u'Hyper Beam': {'DPS': 18.38,
  'Duration': 5000.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 87.5,
  'Type': u'Normal'},
 u'Hyper Fang': {'DPS': 21.88,
  'Duration': 2100.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 43.75,
  'Type': u'Normal'},
 u'Ice Beam': {'DPS': 14.38,
  'Duration': 3650.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 50.0,
  'Type': u'Ice'},
 u'Ice Punch': {'DPS': 13.5,
  'Duration': 3500.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 45.0,
  'Type': u'Ice'},
 u'Ice Shard': {'DPS': 7.14,
  'Duration': 1400.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 10.0,
  'Type': u'Ice'},
 u'Icy Wind': {'DPS': 4.14,
  'Duration': 3800.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 15.0,
  'Type': u'Ice'},
 u'Iron Head': {'DPS': 21.0,
  'Duration': 2000.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 40.0,
  'Type': u'Steel'},
 u'Karate Chop': {'DPS': 9.38,
  'Duration': 800.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 7.0,
  'Power': 7.5,
  'Type': u'Fight'},
 u'Leaf Blade': {'DPS': 20.09,
  'Duration': 2800.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 56.25,
  'Type': u'Grass'},
 u'Lick': {'DPS': 25.0,
  'Duration': 500.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 7.0,
  'Power': 12.5,
  'Type': u'Ghost'},
 u'Low Kick': {'DPS': 10.4,
  'Duration': 600.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 7.0,
  'Power': 6.25,
  'Type': u'Fight'},
 u'Low Sweep': {'DPS': 12.87,
  'Duration': 2550.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Fight'},
 u'Magnet Bomb': {'DPS': 11.72,
  'Duration': 2800.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Steel'},
 u'Megahorn': {'DPS': 18.05,
  'Duration': 3200.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 55.0,
  'Type': u'Bug'},
 u'Metal Claw': {'DPS': 19.0,
  'Duration': 630.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 7.0,
  'Power': 12.0,
  'Type': u'Steel'},
 u'Moonblast': {'DPS': 19.21,
  'Duration': 4100.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Fairy'},
 u'Mud Bomb': {'DPS': 12.62,
  'Duration': 2600.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Ground'},
 u'Mud Shot': {'DPS': 27.27,
  'Duration': 550.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 7.0,
  'Power': 15.0,
  'Type': u'Ground'},
 u'Mud Slap': {'DPS': 4.44,
  'Duration': 1350.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 9.0,
  'Power': 6.0,
  'Type': u'Ground'},
 u'Night Slash': {'DPS': 11.57,
  'Duration': 2700.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Dark'},
 u'Ominous Wind': {'DPS': 8.47,
  'Duration': 3100.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Ghost'},
 u'Peck': {'DPS': 10.9,
  'Duration': 1150.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 10.0,
  'Power': 12.5,
  'Type': u'Flying'},
 u'Petal Blizzard': {'DPS': 20.51,
  'Duration': 3200.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Grass'},
 u'Play Rough': {'DPS': 22.63,
  'Duration': 2900.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Fairy'},
 u'Poison Fang': {'DPS': 6.56,
  'Duration': 2400.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 18.75,
  'Type': u'Poison'},
 u'Poison Jab': {'DPS': 17.86,
  'Duration': 1050.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 7.0,
  'Power': 18.75,
  'Type': u'Poison'},
 u'Poison Sting': {'DPS': 13.04,
  'Duration': 575.0,
  'Energy Cost': '',
  'Energy Per Hit': 4.0,
  'Power': 7.5,
  'Type': u'Poison'},
 u'Pound': {'DPS': 14.8,
  'Duration': 540.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 8.0,
  'Type': u'Normal'},
 u'Power Gem': {'DPS': 14.48,
  'Duration': 2900.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 40.0,
  'Type': u'Rock'},
 u'Power Whip': {'DPS': 26.79,
  'Duration': 2800.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Grass'},
 u'Psybeam': {'DPS': 9.67,
  'Duration': 3800.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 35.0,
  'Type': u'Psychic'},
 u'Psychic': {'DPS': 18.75,
  'Duration': 2800.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 50.0,
  'Type': u'Psychic'},
 u'Psycho Cut': {'DPS': 32.9,
  'Duration': 570.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 7.0,
  'Power': 18.75,
  'Type': u'Psychic'},
 u'Psyshock': {'DPS': 15.56,
  'Duration': 2700.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 0,
  'Power': 50.0,
  'Type': u'Psychic'},
 u'Quick Attack': {'DPS': 9.4,
  'Duration': 1330.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 12.5,
  'Type': u'Normal'},
 u'Razor Leaf': {'DPS': 12.9,
  'Duration': 1450.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 18.75,
  'Type': u'Grass'},
 u'Rock Slide': {'DPS': 13.13,
  'Duration': 3200.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 40.0,
  'Type': u'Rock'},
 u'Rock Smash': {'DPS': 3.55,
  'Duration': 1410.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 7.0,
  'Power': 5.0,
  'Type': u'Fight'},
 u'Rock Throw': {'DPS': 11.0,
  'Duration': 1360.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 7.0,
  'Power': 15.0,
  'Type': u'Rock'},
 u'Rock Tomb': {'DPS': 9.19,
  'Duration': 3400.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Rock'},
 u'Scald': {'DPS': 9.19,
  'Duration': 4000.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 43.75,
  'Type': u'Water'},
 u'Scratch': {'DPS': 20.0,
  'Duration': 500.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 7.0,
  'Power': 10.0,
  'Type': u'Normal'},
 u'Seed Bomb': {'DPS': 16.41,
  'Duration': 2400.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Grass'},
 u'Shadow Ball': {'DPS': 13.64,
  'Duration': 3080.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 40.0,
  'Type': u'Ghost'},
 u'Shadow Claw': {'DPS': 21.1,
  'Duration': 950.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 7.0,
  'Power': 20.0,
  'Type': u'Ghost'},
 u'Signal Beam': {'DPS': 14.82,
  'Duration': 3100.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 43.75,
  'Type': u'Bug'},
 u'Sludge': {'DPS': 10.1,
  'Duration': 2600.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Poison'},
 u'Sludge Bomb': {'DPS': 25.24,
  'Duration': 2600.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Poison'},
 u'Sludge Wave': {'DPS': 23.16,
  'Duration': 3400.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 75.0,
  'Type': u'Poison'},
 u'Solar Beam': {'DPS': 17.41,
  'Duration': 4900.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 81.25,
  'Type': u'Grass'},
 u'Spark': {'DPS': 12.5,
  'Duration': 700.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 4.0,
  'Power': 8.75,
  'Type': u'Electric'},
 u'Splash': {'DPS': 0.0,
  'Duration': 1230.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 0.0,
  'Type': u'Water'},
 u'Steel Wing': {'DPS': 11.28,
  'Duration': 1330.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 4.0,
  'Power': 15.0,
  'Type': u'Steel'},
 u'Stomp': {'DPS': 12.5,
  'Duration': 2100.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 25.0,
  'Type': u'Normal'},
 u'Stone Edge': {'DPS': 26.61,
  'Duration': 3100.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 55.0,
  'Type': u'Rock'},
 u'Struggle': {'DPS': 8.85,
  'Duration': 1695.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 15.0,
  'Type': u'Normal'},
 u'Submission': {'DPS': 18.75,
  'Duration': 2100.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Fight'},
 u'Sucker Punch': {'DPS': 10.0,
  'Duration': 700.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 4.0,
  'Power': 7.0,
  'Type': u'Dark'},
 u'Swift': {'DPS': 10.94,
  'Duration': 3000.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 31.25,
  'Type': u'Normal'},
 u'Tackle': {'DPS': 10.91,
  'Duration': 1100.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 7.0,
  'Power': 12.0,
  'Type': u'Normal'},
 u'Thunder': {'DPS': 19.84,
  'Duration': 4300.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 81.25,
  'Type': u'Electric'},
 u'Thunder Punch': {'DPS': 21.88,
  'Duration': 2400.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 50.0,
  'Type': u'Electric'},
 u'Thunder Shock': {'DPS': 10.4,
  'Duration': 600.0,
  'Energy Cost': 33.0,
  'Energy Per Hit': 7.0,
  'Power': 6.25,
  'Type': u'Electric'},
 u'Thunderbolt': {'DPS': 24.31,
  'Duration': 2700.0,
  'Energy Cost': '',
  'Energy Per Hit': 0,
  'Power': 62.5,
  'Type': u'Electric'},
 u'Twister': {'DPS': 5.83,
  'Duration': 2700.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 15.0,
  'Type': u'Dragon'},
 u'Vice Grip': {'DPS': 7.5,
  'Duration': 2100.0,
  'Energy Cost': 25.0,
  'Energy Per Hit': 0,
  'Power': 15.0,
  'Type': u'Normal'},
 u'Vine Whip': {'DPS': 19.23,
  'Duration': 650.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 12.5,
  'Type': u'Grass'},
 u'Water Gun': {'DPS': 25.0,
  'Duration': 500.0,
  'Energy Cost': 20.0,
  'Energy Per Hit': 7.0,
  'Power': 12.5,
  'Type': u'Water'},
 u'Water Pulse': {'DPS': 11.93,
  'Duration': 3300.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Water'},
 u'Wing Attack': {'DPS': 20.0,
  'Duration': 750.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 7.0,
  'Power': 15.0,
  'Type': u'Flying'},
 u'Wrap': {'DPS': 3.94,
  'Duration': 4000.0,
  'Energy Cost': 100.0,
  'Energy Per Hit': 0,
  'Power': 15.0,
  'Type': u'Normal'},
 u'X-Scissor': {'DPS': 18.75,
  'Duration': 2100.0,
  'Energy Cost': 0,
  'Energy Per Hit': 0,
  'Power': 37.5,
  'Type': u'Bug'},
 u'Zen Headbutt': {'DPS': 14.29,
  'Duration': 1050.0,
  'Energy Cost': 50.0,
  'Energy Per Hit': 4.0,
  'Power': 15.0,
  'Type': u'Psychic'}}

pokemon_dict = {u'Abra': {'Special': (u'Psyshock', u'Signal Beam', u'Shadow Ball'),
  'Standard': (u'Zen Headbutt', ''),
  'Types': (u'Psychic', '')},
 u'Aerodactyl': {'Special': (u'Ancient Power', u'Iron Head', u'Hyper Beam'),
  'Standard': (u'Steel Wing', u'Bite'),
  'Types': (u'Rock', u'Flying')},
 u'Alakazam': {'Special': (u'Psychic', u'Dazzling Gleam', u'Shadow Ball'),
  'Standard': (u'Psycho Cut', u'Confusion'),
  'Types': (u'Psychic', '')},
 u'Arbok': {'Special': (u'Dark Pulse', u'Sludge Wave', u'Gunk Shot'),
  'Standard': (u'Bite', u'Acid'),
  'Types': (u'Poison', '')},
 u'Arcanine': {'Special': (u'Fire Blast', u'Flamethrower', u'Bulldoze'),
  'Standard': (u'Fire Fang', u'Bite'),
  'Types': (u'Fire', '')},
 u'Articuno': {'Special': (u'Ice Beam', u'Icy Wind', u'Blizzard'),
  'Standard': (u'Frost Breath', ''),
  'Types': (u'Ice', u'Flying')},
 u'Beedrill': {'Special': (u'Sludge Bomb', u'Aerial Ace', u'X-Scissor'),
  'Standard': (u'Bug Bite', u'Poison Jab'),
  'Types': (u'Bug', u'Poison')},
 u'Bellsprout': {'Special': (u'Power Whip', u'Sludge Bomb', u'Wrap'),
  'Standard': (u'Vine Whip', u'Acid'),
  'Types': (u'Grass', u'Poison')},
 u'Blastoise': {'Special': (u'Flash Cannon', u'Ice Beam', u'Hydro Pump'),
  'Standard': (u'Water Gun', u'Bite'),
  'Types': (u'Water', '')},
 u'Bulbasaur': {'Special': (u'Sludge Bomb', u'Seed Bomb', u'Power Whip'),
  'Standard': (u'Vine Whip', u'Tackle'),
  'Types': (u'Grass', u'Poison')},
 u'Butterfree': {'Special': (u'Bug Buzz', u'Psychic', u'Signal Beam'),
  'Standard': (u'Bug Bite', u'Confusion'),
  'Types': (u'Bug', u'Flying')},
 u'Caterpie': {'Special': (u'Struggle', '', ''),
  'Standard': (u'Bug Bite', u'Tackle'),
  'Types': (u'Bug', '')},
 u'Chansey': {'Special': (u'Psychic', u'Psybeam', u'Dazzling Gleam'),
  'Standard': (u'Pound', u'Zen Headbutt'),
  'Types': (u'Normal', '')},
 u'Charizard': {'Special': (u'Fire Blast', u'Dragon Claw', u'Flamethrower'),
  'Standard': (u'Ember', u'Wing Attack'),
  'Types': (u'Fire', u'Flying')},
 u'Charmander': {'Special': (u'Flame Charge', u'Flame Burst', u'Flamethrower'),
  'Standard': (u'Ember', u'Scratch'),
  'Types': (u'Fire', '')},
 u'Charmeleon': {'Special': (u'Fire Punch', u'Flame Burst', u'Flamethrower'),
  'Standard': (u'Ember', u'Scratch'),
  'Types': (u'Fire', '')},
 u'Clefable': {'Special': (u'Dazzling Gleam', u'Psychic', u'Moonblast'),
  'Standard': (u'Pound', u'Zen Headbutt'),
  'Types': (u'Fairy', '')},
 u'Clefairy': {'Special': (u'Disarming Voice', u'Body Slam', u'Moonblast'),
  'Standard': (u'Pound', u'Zen Headbutt'),
  'Types': (u'Fairy', '')},
 u'Cloyster': {'Special': (u'Icy Wind', u'Hydro Pump', u'Blizzard'),
  'Standard': (u'Frost Breath', u'Ice Shard'),
  'Types': (u'Water', u'Ice')},
 u'Cubone': {'Special': (u'Bone Club', u'Dig', u'Bulldoze'),
  'Standard': (u'Mud Slap', u'Rock Smash'),
  'Types': (u'Ground', '')},
 u'Dewgong': {'Special': (u'Icy Wind', u'Aqua Jet', u'Blizzard'),
  'Standard': (u'Frost Breath', u'Ice Shard'),
  'Types': (u'Water', u'Ice')},
 u'Diglett': {'Special': (u'Dig', u'Mud Bomb', u'Rock Tomb'),
  'Standard': (u'Mud Shot', u'Scratch'),
  'Types': (u'Ground', '')},
 u'Ditto': {'Special': (u'Struggle', '', ''),
  'Standard': (u'Pound', ''),
  'Types': (u'Normal', '')},
 u'Dodrio': {'Special': (u'Drill Peck', u'Aerial Ace', u'Air Cutter'),
  'Standard': (u'Feint Attack', u'Steel Wing'),
  'Types': (u'Normal', u'Flying')},
 u'Doduo': {'Special': (u'Drill Peck', u'Aerial Ace', u'Swift'),
  'Standard': (u'Peck', u'Quick Attack'),
  'Types': (u'Normal', u'Flying')},
 u'Dragonair': {'Special': (u'Wrap', u'Aqua Tail', u'Dragon Pulse'),
  'Standard': (u'Dragon Breath', ''),
  'Types': (u'Dragon', '')},
 u'Dragonite': {'Special': (u'Dragon Pulse', u'Hyper Beam', u'Dragon Claw'),
  'Standard': (u'Dragon Breath', u'Steel Wing'),
  'Types': (u'Dragon', u'Flying')},
 u'Dratini': {'Special': (u'Wrap', u'Twister', u'Aqua Tail'),
  'Standard': (u'Dragon Breath', ''),
  'Types': (u'Dragon', '')},
 u'Drowzee': {'Special': (u'Psybeam', u'Psyshock', u'Psychic'),
  'Standard': (u'Pound', u'Confusion'),
  'Types': (u'Psychic', '')},
 u'Dugtrio': {'Special': (u'Earthquake', u'Mud Bomb', u'Stone Edge'),
  'Standard': (u'Sucker Punch', u'Mud Shot'),
  'Types': (u'Ground', '')},
 u'Eevee': {'Special': (u'Dig', u'Swift', u'Body Slam'),
  'Standard': (u'Quick Attack', u'Tackle'),
  'Types': (u'Normal', '')},
 u'Ekans': {'Special': (u'Wrap', u'Sludge Bomb', u'Gunk Shot'),
  'Standard': (u'Poison Sting', u'Acid'),
  'Types': (u'Poison', '')},
 u'Electabuzz': {'Special': (u'Thunder Punch', u'Thunderbolt', u'Thunder'),
  'Standard': (u'Thunder Shock', u'Low Kick'),
  'Types': (u'Electric', '')},
 u'Electrode': {'Special': (u'Discharge', u'Thunderbolt', u'Hyper Beam'),
  'Standard': (u'Spark', u'Tackle'),
  'Types': (u'Electric', '')},
 u'Exeggcute': {'Special': (u'Seed Bomb', u'Psychic', u'Ancient Power'),
  'Standard': (u'Confusion', ''),
  'Types': (u'Grass', u'Psychic')},
 u'Exeggutor': {'Special': (u'Seed Bomb', u'Psychic', u'Solar Beam'),
  'Standard': (u'Confusion', u'Zen Headbutt'),
  'Types': (u'Grass', u'Psychic')},
 u"Farfetch'd": {'Special': (u'Aerial Ace', u'Air Cutter', u'Leaf Blade'),
  'Standard': (u'Cut', u'Fury Cutter'),
  'Types': (u'Normal', u'Flying')},
 u'Fearow': {'Special': (u'Aerial Ace', u'Drill Run', u'Twister'),
  'Standard': (u'Peck', u'Steel Wing'),
  'Types': (u'Normal', u'Flying')},
 u'Flareon': {'Special': (u'Fire Blast', u'Flamethrower', u'Heat Wave'),
  'Standard': (u'Ember', ''),
  'Types': (u'Fire', '')},
 u'Gastly': {'Special': (u'Ominous Wind', u'Dark Pulse', u'Sludge Bomb'),
  'Standard': (u'Lick', u'Sucker Punch'),
  'Types': (u'Ghost', u'Poison')},
 u'Gengar': {'Special': (u'Shadow Ball', u'Dark Pulse', u'Sludge Wave'),
  'Standard': (u'Sucker Punch', u'Shadow Claw'),
  'Types': (u'Ghost', u'Poison')},
 u'Geodude': {'Special': (u'Rock Slide', u'Rock Tomb', u'Dig'),
  'Standard': (u'Rock Throw', u'Tackle'),
  'Types': (u'Rock', u'Ground')},
 u'Gloom': {'Special': (u'Petal Blizzard', u'Sludge Bomb', u'Moonblast'),
  'Standard': (u'Razor Leaf', u'Acid'),
  'Types': (u'Grass', u'Poison')},
 u'Golbat': {'Special': (u'Poison Fang', u'Air Cutter', u'Ominous Wind'),
  'Standard': (u'Wing Attack', u'Bite'),
  'Types': (u'Poison', u'Flying')},
 u'Goldeen': {'Special': (u'Water Pulse', u'Horn Attack', u'Aqua Tail'),
  'Standard': (u'Peck', u'Mud Shot'),
  'Types': (u'Water', '')},
 u'Golduck': {'Special': (u'Psychic', u'Hydro Pump', u'Ice Beam'),
  'Standard': (u'Water Gun', u'Confusion'),
  'Types': (u'Water', '')},
 u'Golem': {'Special': (u'Stone Edge', u'Ancient Power', u'Earthquake'),
  'Standard': (u'Rock Throw', u'Mud Shot'),
  'Types': (u'Rock', u'Ground')},
 u'Graveler': {'Special': (u'Dig', u'Stone Edge', u'Rock Slide'),
  'Standard': (u'Rock Throw', u'Mud Shot'),
  'Types': (u'Rock', u'Ground')},
 u'Grimer': {'Special': (u'Sludge', u'Mud Bomb', u'Sludge Bomb'),
  'Standard': (u'Acid', u'Mud Slap'),
  'Types': (u'Poison', '')},
 u'Growlithe': {'Special': (u'Flame Wheel', u'Body Slam', u'Flamethrower'),
  'Standard': (u'Ember', u'Bite'),
  'Types': (u'Fire', '')},
 u'Gyarados': {'Special': (u'Hydro Pump', u'Twister', u'Dragon Pulse'),
  'Standard': (u'Dragon Breath', u'Bite'),
  'Types': (u'Water', u'Flying')},
 u'Haunter': {'Special': (u'Shadow Ball', u'Dark Pulse', u'Sludge Bomb'),
  'Standard': (u'Shadow Claw', u'Lick'),
  'Types': (u'Ghost', u'Poison')},
 u'Hitmonchan': {'Special': (u'Fire Punch', u'Ice Punch', u'Thunder Punch'),
  'Standard': (u'Bullet Punch', u'Rock Smash'),
  'Types': (u'Fight', '')},
 u'Hitmonlee': {'Special': (u'Stomp', u'Low Sweep', u'Stone Edge'),
  'Standard': (u'Low Kick', u'Rock Smash'),
  'Types': (u'Fight', '')},
 u'Horsea': {'Special': (u'Bubble Beam', u'Dragon Pulse', u'Flash Cannon'),
  'Standard': (u'Water Gun', u'Bubble'),
  'Types': (u'Water', '')},
 u'Hypno': {'Special': (u'Psyshock', u'Psychic', u'Shadow Ball'),
  'Standard': (u'Zen Headbutt', u'Confusion'),
  'Types': (u'Psychic', '')},
 u'Ivysaur': {'Special': (u'Sludge Bomb', u'Solar Beam', u'Power Whip'),
  'Standard': (u'Razor Leaf', u'Vine Whip'),
  'Types': (u'Grass', u'Poison')},
 u'Jigglypuff': {'Special': (u'Disarming Voice', u'Body Slam', u'Play Rough'),
  'Standard': (u'Pound', u'Feint Attack'),
  'Types': (u'Normal', u'Fairy')},
 u'Jolteon': {'Special': (u'Discharge', u'Thunderbolt', u'Thunder'),
  'Standard': (u'Thunder Shock', ''),
  'Types': (u'Electric', '')},
 u'Jynx': {'Special': (u'Draining Kiss', u'Ice Punch', u'Psyshock'),
  'Standard': (u'Frost Breath', u'Pound'),
  'Types': (u'Ice', u'Psychic')},
 u'Kabuto': {'Special': (u'Ancient Power', u'Aqua Jet', u'Rock Tomb'),
  'Standard': (u'Scratch', u'Mud Shot'),
  'Types': (u'Rock', u'Water')},
 u'Kabutops': {'Special': (u'Ancient Power', u'Water Pulse', u'Stone Edge'),
  'Standard': (u'Mud Shot', u'Fury Cutter'),
  'Types': (u'Rock', u'Water')},
 u'Kadabra': {'Special': (u'Psybeam', u'Dazzling Gleam', u'Shadow Ball'),
  'Standard': (u'Psycho Cut', u'Confusion'),
  'Types': (u'Psychic', '')},
 u'Kakuna': {'Special': (u'Struggle', '', ''),
  'Standard': (u'Bug Bite', u'Poison Sting'),
  'Types': (u'Bug', u'Poison')},
 u'Kangaskhan': {'Special': (u'Brick Break', u'Earthquake', u'Stomp'),
  'Standard': (u'Mud Slap', u'Low Kick'),
  'Types': (u'Normal', '')},
 u'Kingler': {'Special': (u'Vice Grip', u'X-Scissor', u'Water Pulse'),
  'Standard': (u'Metal Claw', u'Mud Shot'),
  'Types': (u'Water', '')},
 u'Koffing': {'Special': (u'Sludge', u'Sludge Bomb', u'Dark Pulse'),
  'Standard': (u'Acid', u'Tackle'),
  'Types': (u'Poison', '')},
 u'Krabby': {'Special': (u'Vice Grip', u'Bubble Beam', u'Water Pulse'),
  'Standard': (u'Bubble', u'Mud Shot'),
  'Types': (u'Water', '')},
 u'Lapras': {'Special': (u'Dragon Pulse', u'Ice Beam', u'Blizzard'),
  'Standard': (u'Frost Breath', u'Ice Shard'),
  'Types': (u'Water', u'Ice')},
 u'Lickitung': {'Special': (u'Hyper Beam', u'Stomp', u'Power Whip'),
  'Standard': (u'Lick', u'Zen Headbutt'),
  'Types': (u'Normal', '')},
 u'Machamp': {'Special': (u'Stone Edge', u'Submission', u'Cross Chop'),
  'Standard': (u'Bullet Punch', u'Karate Chop'),
  'Types': (u'Fight', '')},
 u'Machoke': {'Special': (u'Submission', u'Brick Break', u'Cross Chop'),
  'Standard': (u'Low Kick', u'Karate Chop'),
  'Types': (u'Fight', '')},
 u'Machop': {'Special': (u'Low Sweep', u'Brick Break', u'Cross Chop'),
  'Standard': (u'Low Kick', u'Karate Chop'),
  'Types': (u'Fight', '')},
 u'Magikarp': {'Special': (u'Struggle', '', ''),
  'Standard': (u'Splash', ''),
  'Types': (u'Water', '')},
 u'Magmar': {'Special': (u'Fire Blast', u'Fire Punch', u'Flamethrower'),
  'Standard': (u'Ember', u'Karate Chop'),
  'Types': (u'Fire', '')},
 u'Magnemite': {'Special': (u'Discharge', u'Magnet Bomb', u'Thunderbolt'),
  'Standard': (u'Spark', u'Thunder Shock'),
  'Types': (u'Electric', u'Steel')},
 u'Magneton': {'Special': (u'Discharge', u'Magnet Bomb', u'Flash Cannon'),
  'Standard': (u'Spark', u'Thunder Shock'),
  'Types': (u'Electric', u'Steel')},
 u'Mankey': {'Special': (u'Cross Chop', u'Low Sweep', u'Brick Break'),
  'Standard': (u'Karate Chop', u'Scratch'),
  'Types': (u'Fight', '')},
 u'Marowak': {'Special': (u'Bone Club', u'Dig', u'Earthquake'),
  'Standard': (u'Mud Slap', u'Rock Smash'),
  'Types': (u'Ground', '')},
 u'Meowth': {'Special': (u'Night Slash', u'Dark Pulse', u'Body Slam'),
  'Standard': (u'Scratch', u'Bite'),
  'Types': (u'Normal', '')},
 u'Metapod': {'Special': (u'Struggle', '', ''),
  'Standard': (u'Bug Bite', u'Tackle'),
  'Types': (u'Bug', '')},
 u'Mew': {'Special': (u'-', u'-', u'-'),
  'Standard': (u'Pound', ''),
  'Types': (u'Psychic', '')},
 u'Mewtwo': {'Special': (u'Psychic', u'Shadow Ball', u'Hyper Beam'),
  'Standard': (u'Psycho Cut', u'Confusion'),
  'Types': (u'Psychic', '')},
 u'Moltres': {'Special': (u'Fire Blast', u'Heat Wave', u'Flamethrower'),
  'Standard': (u'Ember', ''),
  'Types': (u'Fire', u'Flying')},
 u'Mr. Mime': {'Special': (u'Psybeam', u'Psychic', u'Shadow Ball'),
  'Standard': (u'Confusion', u'Zen Headbutt'),
  'Types': (u'Psychic', u'Fairy')},
 u'Muk': {'Special': (u'Dark Pulse', u'Gunk Shot', u'Sludge Wave'),
  'Standard': (u'Acid', u'Poison Jab'),
  'Types': (u'Poison', '')},
 u'Nidoking': {'Special': (u'Earthquake', u'Sludge Wave', u'Megahorn'),
  'Standard': (u'Poison Jab', u'Fury Cutter'),
  'Types': (u'Poison', u'Ground')},
 u'Nidoqueen': {'Special': (u'Earthquake', u'Sludge Wave', u'Stone Edge'),
  'Standard': (u'Poison Jab', u'Bite'),
  'Types': (u'Poison', u'Ground')},
 u'Nidoran F': {'Special': (u'Poison Fang', u'Body Slam', u'Sludge Bomb'),
  'Standard': (u'Bite', u'Poison Sting'),
  'Types': (u'Poison', '')},
 u'Nidoran M': {'Special': (u'Horn Attack', u'Body Slam', u'Sludge Bomb'),
  'Standard': (u'Peck', u'Poison Sting'),
  'Types': (u'Poison', '')},
 u'Nidorina': {'Special': (u'Poison Fang', u'Dig', u'Sludge Bomb'),
  'Standard': (u'Bite', u'Poison Sting'),
  'Types': (u'Poison', '')},
 u'Nidorino': {'Special': (u'Horn Attack', u'Dig', u'Sludge Bomb'),
  'Standard': (u'Poison Jab', u'Poison Sting'),
  'Types': (u'Poison', '')},
 u'Ninetales': {'Special': (u'Heat Wave', u'Flamethrower', u'Fire Blast'),
  'Standard': (u'Feint Attack', u'Ember'),
  'Types': (u'Fire', '')},
 u'Oddish': {'Special': (u'Seed Bomb', u'Sludge Bomb', u'Moonblast'),
  'Standard': (u'Razor Leaf', u'Acid'),
  'Types': (u'Grass', u'Poison')},
 u'Omanyte': {'Special': (u'Ancient Power', u'Brine', u'Rock Tomb'),
  'Standard': (u'Water Gun', u'Mud Shot'),
  'Types': (u'Rock', u'Water')},
 u'Omastar': {'Special': (u'Ancient Power', u'Hydro Pump', u'Rock Slide'),
  'Standard': (u'Rock Throw', u'Water Gun'),
  'Types': (u'Rock', u'Water')},
 u'Onix': {'Special': (u'Rock Slide', u'Stone Edge', u'Iron Head'),
  'Standard': (u'Rock Throw', u'Tackle'),
  'Types': (u'Rock', u'Ground')},
 u'Paras': {'Special': (u'Cross Poison', u'X-Scissor', u'Seed Bomb'),
  'Standard': (u'Scratch', u'Bug Bite'),
  'Types': (u'Bug', u'Grass')},
 u'Parasect': {'Special': (u'Cross Poison', u'X-Scissor', u'Solar Beam'),
  'Standard': (u'Bug Bite', u'Fury Cutter'),
  'Types': (u'Bug', u'Grass')},
 u'Persian': {'Special': (u'Night Slash', u'Power Gem', u'Play Rough'),
  'Standard': (u'Scratch', u'Feint Attack'),
  'Types': (u'Normal', '')},
 u'Pidgeot': {'Special': (u'Hurricane', u'Aerial Ace', u'Air Cutter'),
  'Standard': (u'Wing Attack', u'Steel Wing'),
  'Types': (u'Normal', u'Flying')},
 u'Pidgeotto': {'Special': (u'Twister', u'Aerial Ace', u'Air Cutter'),
  'Standard': (u'Wing Attack', u'Steel Wing'),
  'Types': (u'Normal', u'Flying')},
 u'Pidgey': {'Special': (u'Twister', u'Aerial Ace', u'Air Cutter'),
  'Standard': (u'Quick Attack', u'Tackle'),
  'Types': (u'Normal', u'Flying')},
 u'Pikachu': {'Special': (u'Discharge', u'Thunderbolt', u'Thunder'),
  'Standard': (u'Thunder Shock', u'Quick Attack'),
  'Types': (u'Electric', '')},
 u'Pinsir': {'Special': (u'Vice Grip', u'X-Scissor', u'Submission'),
  'Standard': (u'Rock Smash', u'Fury Cutter'),
  'Types': (u'Bug', '')},
 u'Poliwag': {'Special': (u'Bubble Beam', u'Mud Bomb', u'Body Slam'),
  'Standard': (u'Bubble', u'Mud Shot'),
  'Types': (u'Water', '')},
 u'Poliwhirl': {'Special': (u'Scald', u'Mud Bomb', u'Bubble Beam'),
  'Standard': (u'Bubble', u'Mud Shot'),
  'Types': (u'Water', '')},
 u'Poliwrath': {'Special': (u'Hydro Pump', u'Submission', u'Ice Punch'),
  'Standard': (u'Bubble', u'Mud Shot'),
  'Types': (u'Water', u'Fight')},
 u'Ponyta': {'Special': (u'Flame Charge', u'Flame Wheel', u'Fire Blast'),
  'Standard': (u'Tackle', u'Ember'),
  'Types': (u'Fire', '')},
 u'Porygon': {'Special': (u'Psybeam', u'Signal Beam', u'Discharge'),
  'Standard': (u'Quick Attack', u'Tackle'),
  'Types': (u'Normal', '')},
 u'Primeape': {'Special': (u'Cross Chop', u'Low Sweep', u'Night Slash'),
  'Standard': (u'Low Kick', u'Karate Chop'),
  'Types': (u'Fight', '')},
 u'Psyduck': {'Special': (u'Psybeam', u'Aqua Tail', u'Cross Chop'),
  'Standard': (u'Water Gun', u'Zen Headbutt'),
  'Types': (u'Water', '')},
 u'Raichu': {'Special': (u'Brick Break', u'Thunder Punch', u'Thunder'),
  'Standard': (u'Thunder Shock', u'Spark'),
  'Types': (u'Electric', '')},
 u'Rapidash': {'Special': (u'Fire Blast', u'Drill Run', u'Heat Wave'),
  'Standard': (u'Low Kick', u'Ember'),
  'Types': (u'Fire', '')},
 u'Raticate': {'Special': (u'Dig', u'Hyper Fang', u'Hyper Beam'),
  'Standard': (u'Bite', u'Quick Attack'),
  'Types': (u'Normal', '')},
 u'Rattata': {'Special': (u'Dig', u'Hyper Fang', u'Body Slam'),
  'Standard': (u'Tackle', u'Quick Attack'),
  'Types': (u'Normal', '')},
 u'Rhydon': {'Special': (u'Megahorn', u'Earthquake', u'Stone Edge'),
  'Standard': (u'Mud Slap', u'Rock Smash'),
  'Types': (u'Ground', u'Rock')},
 u'Rhyhorn': {'Special': (u'Bulldoze', u'Horn Attack', u'Stomp'),
  'Standard': (u'Mud Slap', u'Rock Smash'),
  'Types': (u'Ground', u'Rock')},
 u'Sandshrew': {'Special': (u'Dig', u'Rock Slide', u'Rock Tomb'),
  'Standard': (u'Scratch', u'Mud Shot'),
  'Types': (u'Ground', '')},
 u'Sandslash': {'Special': (u'Earthquake', u'Rock Tomb', u'Bulldoze'),
  'Standard': (u'Metal Claw', u'Mud Shot'),
  'Types': (u'Ground', '')},
 u'Scyther': {'Special': (u'Night Slash', u'X-Scissor', u'Bug Buzz'),
  'Standard': (u'Fury Cutter', u'Steel Wing'),
  'Types': (u'Bug', u'Flying')},
 u'Seadra': {'Special': (u'Blizzard', u'Dragon Pulse', u'Hydro Pump'),
  'Standard': (u'Water Gun', u'Dragon Breath'),
  'Types': (u'Water', '')},
 u'Seaking': {'Special': (u'Icy Wind', u'Drill Run', u'Megahorn'),
  'Standard': (u'Peck', u'Poison Jab'),
  'Types': (u'Water', '')},
 u'Seel': {'Special': (u'Aqua Jet', u'Icy Wind', u'Aqua Tail'),
  'Standard': (u'Ice Shard', u'Water Gun'),
  'Types': (u'Water', '')},
 u'Shellder': {'Special': (u'Bubble Beam', u'Water Pulse', u'Icy Wind'),
  'Standard': (u'Ice Shard', u'Tackle'),
  'Types': (u'Water', '')},
 u'Slowbro': {'Special': (u'Water Pulse', u'Psychic', u'Ice Beam'),
  'Standard': (u'Water Gun', u'Confusion'),
  'Types': (u'Water', u'Psychic')},
 u'Slowpoke': {'Special': (u'Water Pulse', u'Psyshock', u'Psychic'),
  'Standard': (u'Water Gun', u'Confusion'),
  'Types': (u'Water', u'Psychic')},
 u'Snorlax': {'Special': (u'Body Slam', u'Hyper Beam', u'Earthquake'),
  'Standard': (u'Zen Headbutt', u'Lick'),
  'Types': (u'Normal', '')},
 u'Spearow': {'Special': (u'Aerial Ace', u'Drill Peck', u'Twister'),
  'Standard': (u'Peck', u'Quick Attack'),
  'Types': (u'Normal', u'Flying')},
 u'Squirtle': {'Special': (u'Aqua Jet', u'Aqua Tail', u'Water Pulse'),
  'Standard': (u'Bubble', u'Tackle'),
  'Types': (u'Water', '')},
 u'Starmie': {'Special': (u'Hydro Pump', u'Power Gem', u'Psybeam'),
  'Standard': (u'Quick Attack', u'Water Gun'),
  'Types': (u'Water', u'Psychic')},
 u'Staryu': {'Special': (u'Swift', u'Bubble Beam', u'Power Gem'),
  'Standard': (u'Quick Attack', u'Water Gun'),
  'Types': (u'Water', '')},
 u'Tangela': {'Special': (u'Power Whip', u'Sludge Bomb', u'Solar Beam'),
  'Standard': (u'Vine Whip', ''),
  'Types': (u'Grass', '')},
 u'Tauros': {'Special': (u'Horn Attack', u'Iron Head', u'Earthquake'),
  'Standard': (u'Tackle', u'Zen Headbutt'),
  'Types': (u'Normal', '')},
 u'Tentacool': {'Special': (u'Bubble Beam', u'Water Pulse', u'Wrap'),
  'Standard': (u'Bubble', u'Poison Sting'),
  'Types': (u'Water', u'Poison')},
 u'Tentacruel': {'Special': (u'Hydro Pump', u'Sludge Wave', u'Blizzard'),
  'Standard': (u'Acid', u'Poison Jab'),
  'Types': (u'Water', u'Poison')},
 u'Vaporeon': {'Special': (u'Water Pulse', u'Hydro Pump', u'Aqua Tail'),
  'Standard': (u'Water Gun', ''),
  'Types': (u'Water', '')},
 u'Venomoth': {'Special': (u'Poison Fang', u'Psychic', u'Bug Buzz'),
  'Standard': (u'Bug Bite', u'Confusion'),
  'Types': (u'Bug', u'Poison')},
 u'Venonat': {'Special': (u'Poison Fang', u'Psybeam', u'Signal Beam'),
  'Standard': (u'Bug Bite', u'Confusion'),
  'Types': (u'Bug', u'Poison')},
 u'Venusaur': {'Special': (u'Sludge Bomb', u'Petal Blizzard', u'Solar Beam'),
  'Standard': (u'Razor Leaf', u'Vine Whip'),
  'Types': (u'Grass', u'Poison')},
 u'Victreebel': {'Special': (u'Leaf Blade', u'Sludge Bomb', u'Solar Beam'),
  'Standard': (u'Razor Leaf', u'Acid'),
  'Types': (u'Grass', u'Poison')},
 u'Vileplume': {'Special': (u'Petal Blizzard', u'Solar Beam', u'Moonblast'),
  'Standard': (u'Razor Leaf', u'Acid'),
  'Types': (u'Grass', u'Poison')},
 u'Voltorb': {'Special': (u'Discharge', u'Thunderbolt', u'Signal Beam'),
  'Standard': (u'Spark', u'Tackle'),
  'Types': (u'Electric', '')},
 u'Vulpix': {'Special': (u'Body Slam', u'Flamethrower', u'Flame Charge'),
  'Standard': (u'Quick Attack', u'Ember'),
  'Types': (u'Fire', '')},
 u'Wartortle': {'Special': (u'Aqua Jet', u'Ice Beam', u'Hydro Pump'),
  'Standard': (u'Water Gun', u'Bite'),
  'Types': (u'Water', '')},
 u'Weedle': {'Special': (u'Struggle', '', ''),
  'Standard': (u'Bug Bite', u'Poison Sting'),
  'Types': (u'Bug', u'Poison')},
 u'Weepinbell': {'Special': (u'Power Whip', u'Sludge Bomb', u'Seed Bomb'),
  'Standard': (u'Razor Leaf', u'Acid'),
  'Types': (u'Grass', u'Poison')},
 u'Weezing': {'Special': (u'Sludge Bomb', u'Shadow Ball', u'Dark Pulse'),
  'Standard': (u'Acid', u'Tackle'),
  'Types': (u'Poison', '')},
 u'Wigglytuff': {'Special': (u'Dazzling Gleam', u'Hyper Beam', u'Play Rough'),
  'Standard': (u'Pound', u'Feint Attack'),
  'Types': (u'Normal', u'Fairy')},
 u'Zapdos': {'Special': (u'Discharge', u'Thunderbolt', u'Thunder'),
  'Standard': (u'Thunder Shock', ''),
  'Types': (u'Electric', u'Flying')},
 u'Zubat': {'Special': (u'Poison Fang', u'Air Cutter', u'Sludge Bomb'),
  'Standard': (u'Quick Attack', u'Bite'),
  'Types': (u'Poison', u'Flying')}}

types_dict = {u'bug': {u'bug': 1.0,
  u'dark': 1.25,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 0.80000000000000004,
  u'fighting': 0.80000000000000004,
  u'fire': 0.80000000000000004,
  u'flying': 0.80000000000000004,
  u'ghost': 0.80000000000000004,
  u'grass': 1.25,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 0.80000000000000004,
  u'psychic': 1.25,
  u'rock': 1.0,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'dark': {u'bug': 1.0,
  u'dark': 0.80000000000000004,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 0.80000000000000004,
  u'fighting': 0.80000000000000004,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 1.25,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.25,
  u'rock': 1.0,
  u'steel': 1.0,
  u'water': 1.0},
 u'dragon': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 1.25,
  u'electric': 1.0,
  u'fairy': 0.80000000000000004,
  u'fighting': 1.0,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 1.0,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'electric': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 0.80000000000000004,
  u'electric': 0.80000000000000004,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 1.0,
  u'flying': 1.25,
  u'ghost': 1.0,
  u'grass': 0.80000000000000004,
  u'ground': 0.80000000000000004,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 1.0,
  u'steel': 1.0,
  u'water': 1.25},
 u'fairy': {u'bug': 1.0,
  u'dark': 1.25,
  u'dragon': 1.25,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.25,
  u'fire': 0.80000000000000004,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 0.80000000000000004,
  u'psychic': 1.0,
  u'rock': 1.0,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'fighting': {u'bug': 0.80000000000000004,
  u'dark': 1.25,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 0.80000000000000004,
  u'fighting': 1.0,
  u'fire': 1.0,
  u'flying': 0.80000000000000004,
  u'ghost': 0.80000000000000004,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.25,
  u'normal': 1.25,
  u'poison': 0.80000000000000004,
  u'psychic': 0.80000000000000004,
  u'rock': 1.25,
  u'steel': 1.25,
  u'water': 1.0},
 u'fire': {u'bug': 1.25,
  u'dark': 1.0,
  u'dragon': 0.80000000000000004,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 0.80000000000000004,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 1.25,
  u'ground': 1.0,
  u'ice': 1.25,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 0.80000000000000004,
  u'steel': 1.25,
  u'water': 0.80000000000000004},
 u'flying': {u'bug': 1.25,
  u'dark': 1.0,
  u'dragon': 1.0,
  u'electric': 0.80000000000000004,
  u'fairy': 1.0,
  u'fighting': 1.25,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 1.25,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 0.80000000000000004,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'ghost': {u'bug': 1.0,
  u'dark': 0.80000000000000004,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 1.25,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 0.80000000000000004,
  u'poison': 1.0,
  u'psychic': 1.25,
  u'rock': 1.0,
  u'steel': 1.0,
  u'water': 1.0},
 u'grass': {u'bug': 0.80000000000000004,
  u'dark': 1.0,
  u'dragon': 0.80000000000000004,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 0.80000000000000004,
  u'flying': 0.80000000000000004,
  u'ghost': 1.0,
  u'grass': 0.80000000000000004,
  u'ground': 1.25,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 0.80000000000000004,
  u'psychic': 1.0,
  u'rock': 1.25,
  u'steel': 0.80000000000000004,
  u'water': 1.25},
 u'ground': {u'bug': 0.80000000000000004,
  u'dark': 1.0,
  u'dragon': 1.0,
  u'electric': 1.25,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 1.25,
  u'flying': 0.80000000000000004,
  u'ghost': 1.0,
  u'grass': 0.80000000000000004,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.25,
  u'psychic': 1.0,
  u'rock': 1.25,
  u'steel': 1.25,
  u'water': 1.0},
 u'ice': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 1.25,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 0.80000000000000004,
  u'flying': 1.25,
  u'ghost': 1.0,
  u'grass': 1.25,
  u'ground': 1.25,
  u'ice': 0.80000000000000004,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 1.0,
  u'steel': 0.80000000000000004,
  u'water': 0.80000000000000004},
 u'normal': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 0.80000000000000004,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 0.80000000000000004,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'poison': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 1.25,
  u'fighting': 1.0,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 0.80000000000000004,
  u'grass': 1.25,
  u'ground': 0.80000000000000004,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 0.80000000000000004,
  u'psychic': 1.0,
  u'rock': 0.80000000000000004,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'psychic': {u'bug': 1.0,
  u'dark': 0.80000000000000004,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.25,
  u'fire': 1.0,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.25,
  u'psychic': 0.80000000000000004,
  u'rock': 1.0,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'rock': {u'bug': 1.25,
  u'dark': 1.0,
  u'dragon': 1.0,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 0.80000000000000004,
  u'fire': 1.25,
  u'flying': 1.25,
  u'ghost': 1.0,
  u'grass': 1.0,
  u'ground': 0.80000000000000004,
  u'ice': 1.25,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 1.0,
  u'steel': 0.80000000000000004,
  u'water': 1.0},
 u'steel': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 1.0,
  u'electric': 0.80000000000000004,
  u'fairy': 1.25,
  u'fighting': 1.0,
  u'fire': 0.80000000000000004,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 1.0,
  u'ground': 1.0,
  u'ice': 1.25,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 1.25,
  u'steel': 0.80000000000000004,
  u'water': 0.80000000000000004},
 u'water': {u'bug': 1.0,
  u'dark': 1.0,
  u'dragon': 0.80000000000000004,
  u'electric': 1.0,
  u'fairy': 1.0,
  u'fighting': 1.0,
  u'fire': 1.25,
  u'flying': 1.0,
  u'ghost': 1.0,
  u'grass': 0.80000000000000004,
  u'ground': 1.25,
  u'ice': 1.0,
  u'normal': 1.0,
  u'poison': 1.0,
  u'psychic': 1.0,
  u'rock': 1.25,
  u'steel': 1.0,
  u'water': 0.80000000000000004}}